# Generated by Django 3.1.7 on 2021-05-20 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cid', models.CharField(max_length=50, unique=True)),
                ('credit', models.IntegerField()),
                ('term', models.CharField(max_length=50)),
                ('depart', models.CharField(max_length=50)),
                ('accept', models.BooleanField(default='', null=True, verbose_name='Accepted')),
                ('description', models.CharField(default='无介绍', max_length=1000)),
                ('keys_tid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher', verbose_name='fk_Course_id')),
            ],
        ),
    ]
