# Generated by Django 3.1.7 on 2021-05-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade_percent',
            field=models.DecimalField(decimal_places=1, default=0.8, max_digits=3),
        ),
    ]
