# Generated by Django 3.1.7 on 2021-05-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='e_grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='p_grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
