# Generated by Django 3.1.5 on 2021-02-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50, unique=True)),
                ('cid', models.CharField(max_length=50, unique=True)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
