# Generated by Django 3.1.5 on 2021-02-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_password'),
        ('course', '0005_auto_20210203_1704'),
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.course', verbose_name='fk_Election_cid'),
        ),
        migrations.AlterField(
            model_name='election',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.student', verbose_name='fk_Election_sid'),
        ),
    ]
