# Generated by Django 3.1.5 on 2021-02-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20210203_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
