# Generated by Django 3.1.5 on 2021-02-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cid', models.CharField(max_length=50, unique=True)),
                ('tid', models.CharField(max_length=50, unique=True)),
                ('credit', models.IntegerField()),
                ('depart', models.CharField(max_length=50)),
                ('keys_tid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher', verbose_name='fk_Course_id')),
            ],
        ),
    ]
