# Generated by Django 3.1.5 on 2021-02-03 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('course', '0002_remove_course_keys_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='keys_tid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher', verbose_name='fk_Course_id'),
            preserve_default=False,
        ),
    ]
