# Generated by Django 3.1.5 on 2021-02-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210203_1637'),
        ('course', '0003_course_keys_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='keys_tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teacher.teacher', verbose_name='fk_Course_id'),
        ),
    ]
