# Generated by Django 3.1.7 on 2021-04-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210203_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(default='202002', max_length=50),
            preserve_default=False,
        ),
    ]
