# Generated by Django 3.1.7 on 2021-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='Accepted'),
        ),
    ]
