# Generated by Django 3.1.7 on 2021-04-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20210427_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='accept',
            field=models.BooleanField(default='', null=True, verbose_name='Accepted'),
        ),
    ]
