# Generated by Django 3.1.7 on 2021-05-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20210427_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='无介绍', max_length=1000),
        ),
    ]
